<h4> Imports

In [18]:
from sent_to_vect import SentenceVectorizer     # custom class import


In [19]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

<h4> Code

## Line-By-Line understandable Code

In [20]:
# question : What is the 2nd law of Thernodynamics ?
correct_answers = ["It is impossible to transfer heat by an automatic machine from a body at lower temperature to a body at a higher temperature without the help of external energy",
                    "Continuous flow of energy cannot be obtained from an object cooling it from its surroundings.",
                    "It is impossible to construct an engine that will extract heat continuously from a heat source and will completely transform into work",
                    "No engine can be built which can extract a fixed amount of heat and will convert it totally into work."
                   ]    # here are all samples of correct answers


given_answer = ["In the world No machine can convert whole heat energy into work"]



### Part1 : Correct answer processing

In [21]:
sTv = SentenceVectorizer()
corr_vector = sTv.sentences_to_vector(correct_answers, Tfidf_vectorizer=False)
corr_vector_features = sTv.get_features_name_out()

In [22]:
corr_vector_features

['amount',
 'automatic',
 'body',
 'built',
 'completely',
 'construct',
 'continuous',
 'continuously',
 'convert',
 'cooling',
 'energy',
 'engine',
 'external',
 'extract',
 'fixed',
 'flow',
 'heat',
 'help',
 'higher',
 'impossible',
 'it',
 'lower',
 'machine',
 'no',
 'object',
 'obtained',
 'source',
 'surroundings',
 'temperature',
 'totally',
 'transfer',
 'transform',
 'without',
 'work']

In [23]:
# corr_vector = np.array(corr_vector)
# corr_vector

### Part2 : Given answer processing

In [24]:
given_vector = sTv.sentences_to_vector(given_answer, Tfidf_vectorizer=False)
given_vector_features = sTv.get_features_name_out()
given_vector_features

['convert', 'energy', 'heat', 'in', 'machine', 'no', 'whole', 'work', 'world']

### Final Part

In [25]:
# \* let's check "given_vector_features" array's all words, If any of them -
#  -doesn't exist- in "corr_vector_features" array , we will add/append it to "corr_vector_features"

for x in given_vector_features:
    if x not in corr_vector_features:
        corr_vector_features.append(x)
        
        temp = []
        for x in corr_vector:
            x.append(0)
            temp.append(x)
            
        corr_vector = temp

In [35]:
corr_vector_features

['amount',
 'automatic',
 'body',
 'built',
 'completely',
 'construct',
 'continuous',
 'continuously',
 'convert',
 'cooling',
 'energy',
 'engine',
 'external',
 'extract',
 'fixed',
 'flow',
 'heat',
 'help',
 'higher',
 'impossible',
 'it',
 'lower',
 'machine',
 'no',
 'object',
 'obtained',
 'source',
 'surroundings',
 'temperature',
 'totally',
 'transfer',
 'transform',
 'without',
 'work',
 'in',
 'whole',
 'world']

Now time to arrange the `vector form` of '**givenAnswer**' by using it's features 

In [27]:
given_vector_features

['convert', 'energy', 'heat', 'in', 'machine', 'no', 'whole', 'work', 'world']

In [28]:
temp = []

for corr in corr_vector_features:
    if corr in given_vector_features:
        temp.append(1)
    else:
        temp.append(0)
            
corr_vector.append(temp)
corr_vector = np.array(corr_vector)
corr_vector


array([[0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 0, 0, 0, 0, 0, 2, 0, 1, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 2, 0, 0, 1, 1, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0],
       [1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1]])

in the `corr_vector` array, the last element contains our given answer tex's vector array

In [29]:
# we will check cosine similarity of that last element with other elements--using cosine similarity

In [30]:
similarity = cosine_similarity(corr_vector)
similarity

array([[1.        , 0.08451543, 0.23904572, 0.07071068, 0.2236068 ],
       [0.08451543, 1.        , 0.        , 0.        , 0.12598816],
       [0.23904572, 0.        , 1.        , 0.42257713, 0.26726124],
       [0.07071068, 0.        , 0.42257713, 1.        , 0.42163702],
       [0.2236068 , 0.12598816, 0.26726124, 0.42163702, 1.        ]])

In [31]:
answer_score = similarity[len(similarity)-1]
answer_score[:-1]

array([0.2236068 , 0.12598816, 0.26726124, 0.42163702])

In [32]:
# our correct answers were stored , let's check the best similar match

In [33]:
print("Best match : ",correct_answers[np.argmax(answer_score[:-1])])
print("Percentage : ",answer_score[np.argmax(answer_score[:-1])],"%")

Best match :  No engine can be built which can extract a fixed amount of heat and will convert it totally into work.
Percentage :  0.4216370213557839 %


## Custom Function 
### (check the above 'Line-By-Line understandale' codes for better understanding)

Now we will bundle all process that done previously - in a custom-function for reusability

In [37]:
def AnswerValidate(CorrectAnswers:list, GivenAnswer:list):
    # part:1
    sTv = SentenceVectorizer()
    corr_vector = sTv.sentences_to_vector(CorrectAnswers, Tfidf_vectorizer=False)
    corr_vector_features = sTv.get_features_name_out()
    
    # part:2
    given_vector = sTv.sentences_to_vector(GivenAnswer, Tfidf_vectorizer=False)
    given_vector_features = sTv.get_features_name_out() 

    # part:FINAL
    # let's check "given_vector_features" array's all words, If any of them -
    # -doesn't exist- in "corr_vector_features" array , we will add/append it to "corr_vector_features"
    for x in given_vector_features:
        if x not in corr_vector_features:
            corr_vector_features.append(x)
            
            temp = []
            for x in corr_vector:
                x.append(0)
                temp.append(x)
                
            corr_vector = temp
            
    # Now time to arrange the `vector form` of '**GivenAnswer**' by using it's features
    temp = []        # vector of the given answer text will be store here

    for corr in corr_vector_features:
        if corr in given_vector_features:
            temp.append(1)
        else:
            temp.append(0)
            
    
    # adding the new vector (of the given answer text) to correct answer's vector array.
    corr_vector.append(temp)
    corr_vector = np.array(corr_vector)
    
    # TIME TO CHECK THE COSINE SIMILARITY
    similarity = cosine_similarity(corr_vector)
    answer_score = similarity[len(similarity)-1]
    print("Best match : ",CorrectAnswers[np.argmax(answer_score[:-1])])
    print("Percentage : ",answer_score[np.argmax(answer_score[:-1])],"%")
    

In [42]:
# question : What is the 2nd law of Thernodynamics ?
correct_answers = ["It is impossible to transfer heat by an automatic machine from a body at lower temperature to a body at a higher temperature without the help of external energy",
                    "Continuous flow of energy cannot be obtained from an object cooling it from its surroundings.",
                    "It is impossible to construct an engine that will extract heat continuously from a heat source and will completely transform into work",
                    "No engine can be built which can extract a fixed amount of heat and will convert it totally into work."
                   ]    # here are all samples of correct answers


given_answer = ["It is impossible to transfer heat from lower temperature to higher temperature, without using any external energy"]



# using custom function
AnswerValidate(correct_answers, given_answer)

Best match :  It is impossible to transfer heat by an automatic machine from a body at lower temperature to a body at a higher temperature without the help of external energy
Percentage :  0.7416198487095663 %
